#include "Application.hpp"
#include "GameState.hpp"
#include "TitleState.hpp"
#include "MenuState.hpp"
#include "PauseState.hpp"
#include "SettingsState.hpp"
#include "GameOverState.hpp"
#include "GameWinState.hpp"
#include "MultiplayerGameState.hpp"
#include "LobbyState.hpp"

const sf::Time Application::kTimePerFrame = sf::seconds(1.f/60.f);

Application::Application() : m_window(sf::VideoMode(1920, 1080), "Networked Game", sf::Style::Close),
	m_player_1_keys(1),
	m_player_2_keys(2),
	m_stack(State::Context(m_window, m_textures, m_fonts, m_music, m_sound, m_player_1_keys, m_player_2_keys))
                             
{
	m_window.setKeyRepeatEnabled(false);

	m_fonts.Load(Font::kMain, "Media/Fonts/BlackRose-2Onld.ttf");
	m_textures.Load(TextureID::kTitleScreen, "Media/Textures/MenuUI/NewMenu.png"); //This image was generated by using ideogram.ai (an Ai generated image)
	m_textures.Load(TextureID::kButtonNormal, "Media/Textures/MenuUI/Option.jpg");
	m_textures.Load(TextureID::kButtonSelected, "Media/Textures/MenuUI/OptionSelected.jpg");
	m_textures.Load(TextureID::kButtonActivated, "Media/Textures/MenuUI/StartSelected.jpg");
	m_textures.Load(TextureID::kButtons, "Media/Textures/Buttons.png");
	m_textures.Load(TextureID::kGameWonSprite, "Media/Textures/MenuUI/Victory.png");
	m_textures.Load(TextureID::kGameLoseSprite, "Media/Textures/MenuUI/Defeat.png");
	m_textures.Load(TextureID::kMenuBoard, "Media/Textures/MenuUI/TITLE.jpg");
	m_textures.Load(TextureID::kLabel, "Media/Textures/MenuUI/LabelBg.png");
	m_textures.Load(TextureID::kLobbyBg, "Media/Textures/MenuUI/Extra.png");

	RegisterStates();
	m_stack.PushState(StateID::kTitle);
}

void Application::Run()
{
	sf::Clock clock;
	sf::Time time_since_last_update = sf::Time::Zero;
	while (m_window.isOpen())
	{
		time_since_last_update += clock.restart();
		while(time_since_last_update > kTimePerFrame)
		{
			time_since_last_update -= kTimePerFrame;
			ProcessInput();
			Update(kTimePerFrame);

			if (m_stack.IsEmpty())
			{
				m_window.close();
			}
		}
		Render();

	}
}

void Application::ProcessInput()
{
	sf::Event event;
	while (m_window.pollEvent(event))
	{
		m_stack.HandleEvent(event);

		if (event.type == sf::Event::Closed)
		{
			m_window.close();
		}
	}
}

void Application::Update(sf::Time dt)
{
	m_stack.Update(dt);
}

void Application::Render()
{
	m_window.clear();
	m_stack.Draw();
	m_window.display();
}

void Application::RegisterStates()
{
	m_stack.RegisterState<TitleState>(StateID::kTitle);
	m_stack.RegisterState<MenuState>(StateID::kMenu);
	m_stack.RegisterState<LobbyState>(StateID::kLobby);
	m_stack.RegisterState<GameState>(StateID::kGame);
	m_stack.RegisterState<MultiplayerGameState>(StateID::kHostGame, true);
	m_stack.RegisterState<MultiplayerGameState>(StateID::kJoinGame, false);
	m_stack.RegisterState<PauseState>(StateID::kPause);
	m_stack.RegisterState<PauseState>(StateID::kNetworkPause, true);
	m_stack.RegisterState<SettingsState>(StateID::kSettings);
	m_stack.RegisterState<GameOverState>(StateID::kGameOver,"Game Over!");
	m_stack.RegisterState<GameWinState>(StateID::kMissionSuccess, "!Congratulations!*You*Won!");
}
